import { ThemeProvider } from "@mui/material/styles";
import CssBaseline from "@mui/material/CssBaseline";
import PropTypes from "prop-types";
import { Inter } from "next/font/google";
import "./globals.css";
import theme from "./theme";
import NavComp from "./component/navbar/navbar.component";
import TopbarComp from "./component/topbar/topbar";
import FooterComp from "./component/footer/footer.component";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider theme={theme}>
          <CssBaseline />
          <TopbarComp />

          <NavComp />
          {children}
          <FooterComp />
        </ThemeProvider>
      </body>
    </html>
  );
}
// Add PropTypes validation
RootLayout.propTypes = {
  children: PropTypes.node.isRequired,
};
